import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import ReactQueryContext from "@/context/ReactQueryContext";
import { ThemeProvider } from "next-themes";
import NavBar from "@/components/shared/navBar/NavBar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children, params }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReactQueryContext>
            <NavBar params={params} />
            {children}
          </ReactQueryContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
