import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import ReactQueryContext from "@/context/ReactQueryContext";
import { ThemeProvider } from "next-themes";
import NavBar from "@/components/shared/navBar/NavBar";
const ibmArabic = IBM_Plex_Sans_Arabic({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-arabic",
  subsets: ["latin", "arabic"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children, params }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmArabic.variable} dark:bg-black dark:text-white`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReactQueryContext>
            <NavBar params={params} />
            {children}
          </ReactQueryContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
